apiVersion: batch/v1
kind: CronJob
metadata:
  name: release-name-zabbix-nodesclean
  labels:
    app: release-name-zabbix-nodesclean
    app.kubernetes.io/name: nodesclean
    app.kubernetes.io/instance: release-name-nodesclean
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccountName: release-name-zabbix
          containers:
          - name: hanodes-autoclean
            image: "postgres:15"
            imagePullPolicy: IfNotPresent
            resources:
              {}
            securityContext:
              {}
            command:
            - /bin/bash
            - -c
            - echo "deleting all stopped and unavailable HANodes older than 3600 seconds..." && psql -c "delete from ha_node where status in (1,2) and extract(epoch from now())-lastaccess>3600"
            env:
            
            
            - name: PGHOST
              value: release-name-zabbix-postgresql
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: zabbixdb-pguser-zabbix
                  key: user
                  optional: true
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbixdb-pguser-zabbix
                  key: password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: zabbixdb-pguser-zabbix
                  key: dbname
                  optional: true
          imagePullSecrets:
          restartPolicy: OnFailure