apiVersion: v1
kind: Secret
metadata:
  name: zabbixdb-pguser-zabbix
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: release-name-zabbix-db-access
    app.kubernetes.io/name: db-access
    helm.sh/chart: zabbix-4.2.1
    app.kubernetes.io/instance: release-name-db-access
    app.kubernetes.io/managed-by: Helm-db-access
type: Opaque
data:
  host: "emFiYml4LXBvc3RncmVzcWw="
  port: "NTQzMg=="
  dbname: "emFiYml4"
  user: "emFiYml4"
  password: "emFiYml4"