apiVersion: v1
kind: Service
metadata:
  name: release-name-zabbix-postgresql
  labels:
    app: release-name-zabbix-postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: release-name-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: db
  selector:
    app: release-name-zabbix-postgresql