apiVersion: v1
kind: Service
metadata:
  name: release-name-zabbix-zabbix-webservice
  labels:
    app: release-name-zabbix-zabbix-webservice
    app.kubernetes.io/name: zabbix-webservice
    app.kubernetes.io/instance: release-name-zabbix-webservice
spec:
  type: ClusterIP
  ports:
    - port: 10053
      targetPort: 10053
      protocol: TCP
      name: webservice
  selector:
    app: release-name-zabbix-zabbix-webservice