apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: release-name-zabbix
  labels:
    app: release-name-zabbix-serviceaccount
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: release-name
