apiVersion: v1
kind: Service
metadata:
  name: release-name-zabbix-zabbix-server
  labels:
    app: release-name-zabbix-zabbix-server
    app.kubernetes.io/name: zabbix-server
    app.kubernetes.io/instance: release-name-zabbix-server
spec:
  type: ClusterIP
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-server
      protocol: TCP
    - port: 10052
      targetPort: 10052
      protocol: TCP
      name: zabbix-jmx
  selector:
    app: release-name-zabbix-zabbix-server