apiVersion: v1
kind: Service
metadata:
  name: my-release-zabbix-zabbix-proxy
  labels:
    app: my-release-zabbix-zabbix-proxy
    app.kubernetes.io/name: zabbix-proxy
    app.kubernetes.io/instance: my-release-zabbix-proxy
spec:
  type: ClusterIP
  ports:
    - port: 10051
      targetPort: 10051
      protocol: TCP
      name: zabbix-proxy
  selector:
    app: my-release-zabbix-zabbix-proxy