apiVersion: v1
kind: Service
metadata:
  name: release-name-zabbix-zabbix-web
  labels:
    app: release-name-zabbix-zabbix-web
    app.kubernetes.io/name: zabbix-web
    app.kubernetes.io/instance: release-name-zabbix-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: zabbix-web
  selector:
    app: release-name-zabbix-zabbix-web